# Generated by Django 5.2.10 on 2026-01-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=300)),
                ('smart_description', models.TextField()),
                ('slides_number', models.IntegerField()),
                ('images_number', models.IntegerField()),
                ('pdf', models.FileField(default='pdf', upload_to='')),
                ('group', models.CharField(choices=[('Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso, Emanuele Cardamuro', 'Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso, Emanuele Cardamuro'), ('Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza, Lorenzo Di Guida', 'Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza, Lorenzo Di Guida'), ('Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti, Francesco Cusati', 'Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti, Francesco Cusati'), ('Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo', 'Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='myapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('slide_text', models.TextField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='myapp.presentation')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.PositiveIntegerField()),
                ('image_file', models.ImageField(default='', upload_to='')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.slide')),
            ],
            options={
                'ordering': ['image_number'],
            },
        ),
    ]
