# Generated by Django 5.2.10 on 2026-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_title',
            field=models.CharField(default='Untitled Slide', max_length=300),
        ),
    ]
