# Generated by Django 5.2.10 on 2026-01-31 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_question_aigeneratedcontent_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
