# Generated by Django 5.2.10 on 2026-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_glossaryterm_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso', 'Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso'), ('Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza', 'Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza'), ('Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti', 'Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti'), ('Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo', 'Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo'), ('Gruppo 5: Emanuele Cardamuro, Lorenzo Di Guida, Paolo Campana, Francesco Cusati, Alessandro De Fenzo', 'Gruppo 5: Emanuele Cardamuro, Lorenzo Di Guida, Paolo Campana, Francesco Cusati, Alessandro De Fenzo')], max_length=300),
        ),
    ]
