# Generated by Django 5.2.10 on 2026-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_article_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso, Emanuele Cardamuro', 'Gruppo 1: Emanuele Magno, Lara Maglione, Antonio De Luca, Luca Pelerusso, Emanuele Cardamuro'), ('Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza, Lorenzo Di Guida', 'Gruppo 2: Carmine Ciccarelli, Filippo Cuccurullo, Giuseppe Cotrufo, Antonio Ventriglia, Antonio De Fenza, Lorenzo Di Guida'), ('Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti, Francesco Cusati', 'Gruppo 3: Lorenzo Famularo, Giuseppe Luongo, Francesco La Marca, Antonio Talotti, Francesco Cusati'), ('Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo', 'Gruppo 4: Alejandro Russo, Francesco Cotroneo, Paolo Campana, Emanuele Iuliano, Alessandro De Fenzo')], max_length=300),
        ),
    ]
