from django.contrib import admin
from .models import Article, Presentation, Slide, Image, Annotation, AnnotationReply, Quiz, Question, Answer, QuizAttempt, QuestionResponse,GlossaryTerm, HistoricalEvent, PageView,Interaction, Reaction, DiscussionTopic, DiscussionPost, StudentProgress, AIGeneratedContent, CollaborativeNote
# Register your models here.
admin.site.register(Article)
admin.site.register(Presentation)
admin.site.register(Slide)
admin.site.register(Image)
admin.site.register(Annotation)
admin.site.register(AnnotationReply)
admin.site.register(Quiz)
admin.site.register(QuizAttempt)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(QuestionResponse)
admin.site.register(GlossaryTerm)
admin.site.register(HistoricalEvent)
admin.site.register(PageView)
admin.site.register(Interaction)
admin.site.register(Reaction)
admin.site.register(DiscussionTopic)
admin.site.register(DiscussionPost)
admin.site.register(StudentProgress)
admin.site.register(AIGeneratedContent)
admin.site.register(CollaborativeNote)